name: infinite_calendar_view
description: A Flutter package allows you to easily implement all calendar views.
version: 1.1.5
homepage: https://github.com/pickywawa/infinite_calendar_view
issue_tracker: https://github.com/pickywawa/infinite_calendar_view/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sticky_infinite_list: ^4.0.1    # infinite listview for events days list

dev_dependencies:
  lints:
  flutter_test:
    sdk: flutter
